### ISSUE TITLE
literally no point

### ISSUE THREAD

**Issue by ghost** [I2rys/ld#1]
what is the point of literally just formatting an api response, that isnt your api, and calling it a project.  literally just farming commits with no point, over 200 repos and 50 followers not a good look. also, you shared your private key, so thanks for that

also recode social synapse in an acceptable clientside language and stop pasting

**Comment by vividsec** [comment]
LOL FR ONG

**Comment by I2rys** [comment]
> what is the point of literally just formatting an api response, that isnt your api, and calling it a project. literally just farming commits with no point, over 200 repos and 50 followers not a good look. also, you shared your private key, so thanks for that
> 
> also recode social synapse in an acceptable clientside language and stop pasting

Hello,
I'm actually trying challenge my self by trying to contributes daily with new ideas but It just sometimes I lack ideas, and about the key It's actually public, everytime you request on the website It will give you a key without login so It's not a problem at all and the SocialSynapse there is nothing wrong with it. 👍🏼

**Comment by ghost** [comment]
youre using compiled nodejs for a client app and only premade packages, i hardly call that a challenge
